image: node:8.11.4-jessie

cache:
  paths:
    - node_modules/

deploy_production:
  stage: deploy
  environment: Production
  only:
    - master
  script:
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/hls-052-nka-backend.git
    - git push -f heroku maste